version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tracker:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=tracker.settings

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=tracker
      - POSTGRES_USER=sinortax
      - POSTGRES_PASSWORD=897746183564163
  redis:
    image: redis:alpine

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: celery -A tracker worker -l info -P eventlet
    volumes:
      - ./tracker:/app
    depends_on:
      - db
      - redis
    env_file: .env
    environment:
      - DJANGO_SETTINGS_MODULE=tracker.settings
      - C_FORCE_ROOT=1
volumes:
  postgres_data: