version: '3'
services:
  web:
    build: ./tracker
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./tracker:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: tracker
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345678
    expose:
      - 5432
volumes:
  pgdata:
