# Generated by Django 5.1.3 on 2024-11-05 10:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_usermodel_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='participates',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
