# Generated by Django 5.1.3 on 2024-11-07 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_role_taskpriority_taskstatus_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Имя"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Фамилия"),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        default="default_avatar.png",
                        null=True,
                        upload_to="avatars/",
                        verbose_name="Аватар",
                    ),
                ),
                (
                    "projects",
                    models.ManyToManyField(
                        related_name="projects",
                        to="main.project",
                        verbose_name="Текущие проекты",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="main.role",
                        verbose_name="Роль",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="project",
            name="users",
            field=models.ManyToManyField(
                through="main.UserProjectAssignment", to="main.user"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="assignee",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignee",
                to="main.user",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="tester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.user",
            ),
        ),
        migrations.AlterField(
            model_name="taskcomment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.user"
            ),
        ),
        migrations.AlterField(
            model_name="userprojectassignment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.user"
            ),
        ),
        migrations.DeleteModel(
            name="UserModel",
        ),
    ]
