# Generated by Django 5.1.3 on 2024-11-07 10:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin", "0003_logentry_add_action_flag_choices"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("main", "0007_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="UserModel",
        ),
    ]
