# Generated by Django 5.1.3 on 2024-11-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_user_usermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='projects',
            field=models.ManyToManyField(null=True, related_name='projects', to='main.project', verbose_name='Текущие проекты'),
        ),
    ]
