name: Django Coverage

on:
  push:
    branches: [ "test" ]
  pull_request:
    branches: [ "test" ]

jobs:
  container-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_DB: tracker
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      # Downloads a copy of the code in your repository before running CI tests
      - name: Check out repository code
        uses: actions/checkout@v4
        
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run migrations
        run : |
          cd tracker
          python manage.py makemigrations
          python manage.py migrate
          
      - name: set up superuser
        run: |
          cd tracker
          python manage.py createsuperuser --email test@email.com --noinput
        env:
          DJANGO_SUPERUSER_PASSWORD: 12345678
          DJANGO_SUPERUSER_USERNAME: arsolovov

      - name: Run Tests
        run: |
          cd tracker
          python manage.py test
        env:
          DB_NAME: tracker
          DB_USER: postgres
          DB_PASSWORD: postgres
          DB_HOST: localhost
          SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
          GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
          USER_NAME: arsolovov
          USER_PASSWORD: 12345678
