name: Django Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }} 
          POSTGRES_DB: tracker
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9, 3.10, 3.11]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run migrations
      run : |
        cd tracker
        python manage.py makemigrations
        python manage.py migrate
        
    - name: set up superuser
      run: |
        python manage.py createsuperuser --noinput
      env:
        DJANGO_SUPERUSER_PASSWORD: ${{ secrets.USER_PASSWORD }}
        DJANGO_SUPERUSER_USERNAME: ${{ secrets.USER_NAME }}
        
    - name: Run Tests
      run: |
        python manage.py test
      env:
        DB_NAME: tracker
        DB_USER: postgres
        DB_PASSWORD: ${{ secrets.DP_PASSWORD }}
        DB_HOST: 127.0.0.1
        SECRET_KEY: ${{ secrets.SECRET_KEY }} 
        SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
        GOOGLE_KEY: ${{ secrets.GOOGLE_KEY }}
        USER_NAME: ${{ secrets.USER_NAME }}
        USER_PASSWORD: ${{ secrets.USER_PASSWORD }}

